routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('clear-cache', function () {
    $exitCode = Artisan::call('config:clear');
    $exitCode1 = Artisan::call('cache:clear');
    $exitCode2 = Artisan::call('route:clear');
    $exitCode3 = Artisan::call('view:clear');
    return redirect('/');
});

Route::prefix('admin')->group(function () {
    Auth::routes(['register' => false, 'reset' => false]);
});



Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::view('chat', 'admin.chat')->name('chat');
    Route::get('chat/get_messages/{user_id}/{limit?}/{offset?}', 'Admin\ChatController@get_messages');
    Route::post('chat/auth', 'Admin\ChatController@auth');
    Route::post('chat/send_message', 'Admin\ChatController@send_message');
    Route::get('/home', 'Admin\IndexController@index')->name('indexPage');
    Route::get('/overall/{type}', 'Admin\IndexController@overall')->name('overall');
    Route::get('/overall/{type}/{chef}', 'Admin\IndexController@overall');
    Route::view('settings', 'admin.settings')->name('settings');
    Route::post('save/data', 'Admin\IndexController@saveData')->name('saveData');
    Route::post('update/password', 'Admin\IndexController@updatePassword')->name('updatePassword');
    Route::view('addRestaurant', 'admin.restaurant.addRestaurant')->name('addRestaurantPage');
    Route::post('addRestaurant', 'Admin\RestaurantController@saveRestaurant')->name('saveRestaurant');
    Route::get('restaurants', 'Admin\RestaurantController@index')->name('restaurantsListPage');
    Route::get('delete/restaurant/{id}', 'Admin\RestaurantController@softDelete')->name('deleteRestaurant');
    // Chef side
    Route::get('chefs/tickets/{type}', 'Admin\ChefController@tickets')->name('chefTickets');
    Route::get('chefs/ticket/conversation/{id}', 'Admin\ChefController@ticket')->name('chefTicket');
    Route::get('chefs', 'Admin\ChefController@index')->name('chefsListPage');
    Route::get('chef/detail/{chef}', 'Admin\ChefController@show')->name('chefPage');
    Route::get('verify/chef/{id}', 'Admin\ChefController@verify')->name('verifyChef');
    Route::get('delete/chef/{id}', 'Admin\ChefController@softDelete')->name('deleteChef');
    Route::get('update/range/chef/{id}', 'Admin\ChefController@updateRange')->name('updateChefRange');
    // Customer side
    Route::get('customers/tickets/{type}', 'Admin\CustomerController@tickets')->name('customerTickets');
    Route::get('customers/ticket/conversation/{id}', 'Admin\CustomerController@ticket')->name('customerTicket');
    Route::get('customers', 'Admin\CustomerController@index')->name('customersListPage');
    Route::get('customers/{id}', 'Admin\CustomerController@show')->name('customersDetailPage');
    Route::get('delete/customer/{id}', 'Admin\CustomerController@softDelete')->name('deleteCustomer');
    // Order Side
    Route::get('daily/orders', 'Admin\OrderController@index')->name('ordersListPage');
    Route::get('orders/{id}', 'Admin\OrderController@show')->name('orderDetail');
    Route::get('orders/chefs/{restaurant}', 'Admin\OrderController@getChefs')->name('getChefs');
    Route::get('delete/order/{id}', 'Admin\OrderController@softDelete')->name('deleteOrder');
    Route::post('assign/order/{id}', 'Admin\OrderController@assignOrder')->name('admin.chef.assign');

    Route::get('sales', 'Admin\IndexController@sales')->name('sales');
    Route::get('top/sales/dishes', 'Admin\IndexController@topSales')->name('topSales');

    Route::get('special', 'Site\ChefController@special')->name('special');
    Route::get('special/pending', 'Site\ChefController@unapprovedSpecial')->name('unapprovedSpecial');
    Route::get('items', 'Site\ChefController@items')->name('items');
    Route::get('item/{id}', 'Site\ChefController@item')->name('item');
    Route::get('item', 'Site\ChefController@addItem')->name('addItem');
    Route::post('item', 'Site\ChefController@storeItem')->name('storeItem');
    Route::get('item/{id}/edit', 'Site\ChefController@edit')->name('editItem');
    Route::post('item/{id}/update', 'Site\ChefController@update')->name('updateItem');
    Route::get('delete/{id}', 'Site\ChefController@softDelete')->name('deleteItem');

    Route::get('categories', 'Site\ChefController@categories')->name('categories');
    Route::get('category/{id}', 'Site\ChefController@category')->name('category');
    Route::get('category', 'Site\ChefController@addCategory')->name('addCategory');
    Route::post('category', 'Site\ChefController@storeCategory')->name('storeCategory');
    Route::get('category/{id}/edit', 'Site\ChefController@editCategory')->name('editCategory');
    Route::post('category/{id}/update', 'Site\ChefController@updateCategory')->name('updateCategory');
    Route::get('delete/category/{id}', 'Site\ChefController@deleteCategory')->name('deleteCategory');


    Route::get('chef/support', 'Admin\IndexController@chefSupports')->name('chefSupports');
    Route::get('customer/support', 'Admin\IndexController@customerSupports')->name('customerSupports');
    Route::get('rider/support', 'Admin\IndexController@riderSupports')->name('riderSupports');
    Route::get('chef/reply/{person}/{id}', 'Admin\IndexController@reply')->name('chefReply');
    Route::get('customer/reply/{person}/{id}', 'Admin\IndexController@reply')->name('customerReply');
    Route::get('rider/reply/{person}/{id}', 'Admin\IndexController@reply')->name('riderReply');
    Route::post('send/reply', 'Admin\IndexController@sendReply')->name('sendReply');

    Route::get('chef/requests', 'Admin\IndexController@chefRequests')->name('chefRequests');
    Route::get('chef/request/approve/{id}', 'Admin\IndexController@chefRequestApprove')->name('chefRequestApprove');
    Route::get('special/approve/{id}', 'Admin\IndexController@approveSpecial');
    // Rider side
    Route::get('riders/tickets/{type}', 'Admin\RiderController@tickets')->name('riderTickets');
    Route::get('riders/ticket/conversation/{id}', 'Admin\RiderController@ticket')->name('riderTicket');
    Route::get('riders', 'Admin\RiderController@index')->name('ridersListPage');
    Route::get('rider/{rider}', 'Admin\RiderController@show')->name('riderPage');
    Route::get('verify/rider/{id}', 'Admin\RiderController@verify')->name('verifyRider');
    Route::get('delete/rider/{id}', 'Admin\RiderController@softDelete')->name('deleteRider');
});
// Chef works
Route::prefix('chef')->as('chef.')
    ->group(function () {
        Route::get('register', 'Auth\ChefAuthController@showRegisterForm')->name('register');
        Route::post('register', 'Auth\ChefAuthController@register')->name('register');
        Route::get('login', 'Auth\ChefAuthController@showLoginForm')->name('login');
        Route::post('login', 'Auth\ChefAuthController@login')->name('login');
        Route::middleware('auth:chef')->group(function () {
            Route::get('logout', 'Auth\ChefAuthController@logout')->name('logout');
            Route::get('settings/{id}', 'Site\ChefController@settingsForm')->name('settings');
            Route::post('settings/{id}', 'Site\ChefController@setting');
            Route::get('/', 'Site\ChefController@index')->name('index');
            Route::get('orders', 'Site\ChefController@orders')->name('myOrders');
            Route::get('orders/{id}', 'Site\ChefController@showOrder')->name('orderDetail');
            Route::get('order/accept/{id}', 'Site\ChefController@acceptOrder')->name('acceptOrder');
        });
        // Route::get('order/decline/{id}', 'Site\ChefController@showOrder')->name('orderDetail');
        /*Route::post('orders/assign', 'Site\ChefController@assignRider')->name('assignRider');
        Route::get('items', 'Site\ChefController@items')->name('items');
        Route::get('item/{id}', 'Site\ChefController@item')->name('item');
        Route::get('item', 'Site\ChefController@addItem')->name('addItem');
        Route::post('item', 'Site\ChefController@storeItem')->name('storeItem');
        Route::get('item/{id}/edit', 'Site\ChefController@edit')->name('editItem');
        Route::post('item/{id}/update', 'Site\ChefController@update')->name('updateItem');
        Route::get('delete/{id}', 'Site\ChefController@softDelete')->name('deleteItem');*/
    });
// Customer Logins
Route::get('register', 'Auth\CustomerAuthController@showRegisterForm')->name('customerRegister');
Route::post('register', 'Auth\CustomerAuthController@register')->name('customer.register');
Route::get('login', 'Auth\CustomerAuthController@showLoginForm')->name('customerLogin');
Route::post('login', 'Auth\CustomerAuthController@login')->name('customer.login');
Route::get('logout', 'Auth\CustomerAuthController@logout')->name('customer.logout');
Route::get('auth/facebook', 'Auth\CustomerAuthController@redirectToFacebook');
Route::get('callback/facebook', 'Auth\CustomerAuthController@handleFacebookCallback');
Route::get('auth/google', 'Auth\CustomerAuthController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\CustomerAuthController@handleGoogleCallback');

Route::get('/', 'Site\IndexController@index')->name('index');
Route::get('/autocomplete', 'Site\IndexController@autocomplete')->name('autocomplete');
Route::get('/search-result/{name}', 'Site\IndexController@search_result');
Route::post('/searching', 'Site\IndexController@searching_result')->name('searching');
Route::get('item/{id}', 'Site\IndexController@itemDetail');
Route::get('chef/{id}', 'Site\IndexController@chefDetail')->name('breakFast');
Route::get('checkout', 'Site\CheckoutController@checkoutForm')->name('checkout');
Route::post('stripe-payment', 'Site\CheckoutController@store')->name('stripe.store');
Route::get('foods', 'Site\IndexController@list')->name('foodDetail');
Route::get('foods/{type}', 'Site\IndexController@list');
Route::get('location/{place}/{lat}/{lng}', 'Site\IndexController@saveLocation');

app/Chef.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Model;

class Chef extends Model
{
    protected $guarded = ['id'];
    protected $hidden = [
        'password','created_at', 'updated_at',
    ];
}

app/Http/Controllers/Admin/ChefController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Chat;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Chef;
use App\ChefTiming;
use App\Mail\ApproveChef;
use App\Order;
use App\Ticket;
use DateTime;
use Illuminate\Support\Facades\Mail;

class ChefController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->type == '')
            $chefs = Chef::get();
        if ($request->type == 'suspended')
            $chefs = Chef::where('suspended', 1)->get();
        if ($request->type == 'active') {
            $get = Chef::get();
            $ids = [];
            foreach ($get as $item) {
                date_default_timezone_set($item->timezone);
                $yesterday = date('l', strtotime("-1 days"));
                $time = date('H:i');
                $day = date('l');
                $getTime = ChefTiming::where('chef_id', $item->id)->where('day', $day)->first();
                $yesterdayTime = ChefTiming::where('chef_id', $item->id)->where('day', $yesterday)->first();
                if ($yesterdayTime) {
                    if ($yesterdayTime->time != 'Closed') {
                        $breakTime = explode('-', $yesterdayTime->time);
                        $startTime = date_format(date_create($breakTime[0]), 'H:i');
                        $startTimeHour = date_format(date_create($breakTime[0]), 'H');
                        $endTime = date_format(date_create($breakTime[1]), 'H:i');
                        $endTimeHour = date_format(date_create($breakTime[1]), 'H');
                        if ($endTime < $startTime)
                            $ids[] = $item->id;
                    }
                }
                if (!$getTime)
                    continue;
                else {
                    if ($getTime->time == 'Closed')
                        continue;
                    else {
                        $breakTime = explode('-', $getTime->time);
                        $startTime = date_format(date_create($breakTime[0]), 'H:i');
                        $endTime = date_format(date_create($breakTime[1]), 'H:i');
                        $dateA = date('Y-m-d H:m:s');
                        $d1 = new DateTime($startTime);
                        $d2 = new DateTime();
                        $interval = $d1->diff($d2);
                        if ($interval->invert == 1 && $interval->i <= 30)
                            continue;
                        if ($startTime > $time)
                            continue;
                        elseif ($endTime < $startTime)
                            $ids[] = $item->id;
                        elseif ($startTime <= $time && $endTime > $time) {
                            $ids[] = $item->id;
                        } elseif ($endTime < $time)
                            continue;
                    }
                }
            }
            $chefs = Chef::whereIn('id', $ids)->get();
        }
        if ($request->type == 'inactive') {
            $get = Chef::get();
            $ids1 = [];
            foreach ($get as $check) {
                date_default_timezone_set($check->timezone);
                $yesterday = date('l', strtotime("-1 days"));
                $time = date('H:i');
                $day = date('l');
                $getTime = ChefTiming::where('chef_id', $check->id)->where('day', $day)->first();
                if (!$getTime)
                    $ids1[] = $check->id;
                else {
                    if ($getTime->time == 'Closed')
                        $ids1[] = $check->id;
                    else {
                        $breakTime = explode('-', $getTime->time);
                        $startTime = date_format(date_create($breakTime[0]), 'H:i');
                        $endTime = date_format(date_create($breakTime[1]), 'H:i');
                        $dateA = date('Y-m-d H:m:s');
                        $d1 = new DateTime($startTime);
                        $d2 = new DateTime();
                        $interval = $d1->diff($d2);
                        if ($interval->invert == 1 && $interval->i <= 30)
                            $ids1[] = $check->id;
                        if ($startTime > $time)
                            $ids1[] = $check->id;
                        elseif ($endTime < $startTime)
                            continue;
                        elseif ($startTime <= $time && $endTime > $time) {
                            continue;
                        } elseif ($endTime < $time)
                            $ids1[] = $check->id;
                    }
                }
            }
            $chefs = Chef::whereIn('id', $ids1)->get();
        }
        return view('admin.chef.chefs', compact('chefs'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show(Chef $chef)
    {
        $breakfast = Order::where('chef_id', $chef->id)->whereTime('created_at', '>', '06:00:00')->whereTime('created_at', '<', '12:00:00')->count();
        $lunch = Order::where('chef_id', $chef->id)->whereTime('created_at', '>', '12:00:00')->whereTime('created_at', '<', '18:00:00')->count();
        $dinner = Order::where('chef_id', $chef->id)->whereTime('created_at', '>', '18:00:00')->whereTime('created_at', '<', '24:00:00')->count();
        $midnight = Order::where('chef_id', $chef->id)->whereTime('created_at', '>', '24:00:00')->whereTime('created_at', '<', '06:00:00')->count();
        return view('admin.chef.chef', compact('chef', 'breakfast', 'lunch', 'dinner', 'midnight'));
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function softDelete($id)
    {
        $chef = Chef::find($id);
        if ($chef) {
            if ($chef->suspended == 0)
                $chef->suspended = 1;
            elseif ($chef->suspended == 1)
                $chef->suspended = 0;
            $chef->save();
            return redirect()->back()->with('message', ($chef->suspended == 1) ? 'Chef suspended' : 'Chef unsuspended');
        } else
            return back()->with('error', 'No chef found');
    }

    public function updateRange($id, Request $request)
    {
        $chef = Chef::find($id);
        if ($chef) {
            $chef->order_range = $request->range;
            $chef->save();
            return redirect()->back()->with('message', 'Chef range updated');
        }
    }

    public function verify($id)
    {
        $find = Chef::find($id);
        if ($find != null) {
            Mail::to($find->email)->send(new ApproveChef($find->first_name . ' ' . $find->last_name));
            $update = Chef::where('id', $id)->update(['approved' => 1]);
            if ($update)
                return back()->with('message', 'Chef verified');
        } else
            return back()->with('error', 'No chef found');
    }

    public function tickets($type)
    {
        $tickets = Ticket::where('status', $type)->where('chef_id', '!=', 0)->latest()->Paginate(25);
        return view('admin.ticket.chef.index', compact('tickets', 'type'));
    }

    public function ticket($id)
    {
        $ticket = Ticket::find($id);
        if ($ticket) {
            $messages = Chat::select('id', 'from', 'to', 'from_to', 'message', 'is_read', 'time', 'created_at')->where('ticket_id', $id)->get();
            return view('admin.ticket.chef.show', compact('ticket', 'messages'));
        } else
            return redirect()->back()->with('error', 'No ticket found');
    }
}

resources/views/site/chef/login.blade.php
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title> Menurie - Chef login</title>
    @include('site.chef.layouts.styles')
</head>
<!-- END: Head-->
<!-- BEGIN: Body-->
<body class="vertical-layout vertical-menu-modern 1-column  navbar-sticky footer-static bg-full-screen-image  blank-page blank-page" data-open="click" data-menu="vertical-menu-modern" data-col="1-column">
    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="content-wrapper">
            <div class="content-header row">
            </div>
            <div class="content-body">
                <!-- login page start -->
                <section id="auth-login" class="row flexbox-container">
                    <div class="col-xl-2 col-2">
                    <img src="{{ asset('site/asset/images/header12.png') }}" alt="">
                    </div>
                    <div class="col-xl-8 col-8">
                        <div class="card bg-authentication mb-0">
                            <div class="row m-0">
                                <!-- left section-login -->
                                <div class="col-md-6 col-sm-12 px-0">
                                    <div class="card disable-rounded-right mb-0 p-2 h-100 d-flex justify-content-center">
                                        <div class="card-header pb-1">
                                            <div class="card-title">
                                                <h4 class="text-center mb-2">Welcome Back</h4>
                                            </div>
                                        </div>
                                        <div class="card-content">
                                            <div class="card-body">
                                                <div class="divider">
                                                    <div class="divider-text text-uppercase text-muted"><small> login with
                                                            email</small>
                                                    </div>
                                                </div>
                                                <form method="POST" action="{{ route('chef.login') }}">
                                                    @csrf
                                                    <div class="form-group mb-50">
                                                        <label class="text-bold-600" for="exampleInputEmail1">Email address</label>
                                                        <input type="email" class="form-control @error('email') is-invalid @enderror" id="exampleInputEmail1" name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>
                                                        @error('email')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span>
                                                        @enderror
                                                    </div>
                                                    <div class="form-group">
                                                        <label class="text-bold-600" for="exampleInputPassword1">Password</label>
                                                        <input type="password" class="form-control @error('password') is-invalid @enderror" id="exampleInputPassword1" placeholder="Password" name="password" required autocomplete="current-password">
                                                        @error('password')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span>
                                                        @enderror
                                                    </div>
                                                    <button type="submit" class="btn btn-menurie glow w-100 position-relative">Login<i id="icon-arrow" class="bx bx-right-arrow-alt"></i></button>
                                                </form>
                                                <hr>
                                                <div class="text-center"><small class="mr-25">New to Menurie?</small><a href="{{route('chef.register')}}"><small>Sign up</small> </a></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- right section image -->
                                <div class="col-md-6 d-md-block d-none text-center align-self-center p-3">
                                    <div class="card-content">
                                    <img class="img-fluid" src="{{ asset('site/asset/images/login-img1.png') }}" alt="branding logo">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-2">
                        <img src="{{ asset('site/asset/images/header2.png') }}" alt="">
                        </div>
                </section>
                <!-- login page ends -->
            </div>
        </div>
    </div>
    <!-- END: Content-->
    @include('site.chef.layouts.scripts')
</body>
<!-- END: Body-->
</html>

resources/views/site/chef/main.blade.php
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->
<head>
    <title>Menurie - Chef Admin Panel</title>
    @include('site.chef.layouts.meta')
    @include('site.chef.layouts.styles')
    @yield('styles')
</head>
<!-- END: Head-->
@include('site.chef.layouts.header')
@include('site.chef.layouts.sidebar')
@yield('content')
@include('site.chef.layouts.footer')